description = "Virtualization packages."
providers = ["dnf", "rpm-ostree"]
packages = [
  "cockpit",
  "cockpit-machines",
  "guestfs-tools",
  "qemu-kvm-core",
  "virt-install",
]
remove = []
flatpaks = []
kargs = []
