name = "bluefin"
description = "Bluefin GNOME workstation setup"
inherits = ["gnome"]

[install]
groups = ["bluefin-deps", "bluefin-brew"]
actions = ["enable-hibernation"]

[software]
shims = true
targets = []

[gnome]
extensions = [
  "settings-updatecheck@localhost",
  "settings-notification-ticker@localhost",
]
remote_extensions = [
  "Panel_Favorites@rmy.pobox.com",
  "panel-workspace-scroll@polymeilex.github.io",
  "appindicatorsupport@rgcjonas.gmail.com",
  "bazaar-integration@kolunmi.github.io",
  "blur-my-shell@aunetx",
  "caffeine@patapon.info",
  "dash-to-dock@micxgx.gmail.com",
  "transparent-top-bar@ftpix.com",
]
